FROM node:22-bookworm

RUN apt-get update && \
  apt-get install -y --no-install-recommends postgresql-client && \
  rm -rf /var/lib/apt/lists/*

RUN node --version && npm --version && psql --version
